# Copyright (C) 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.appservice.apprecordreplay}}
  name: {{.Values.edgex.app.appservice.apprecordreplay}}
spec:
  ports:
  - name: "http"
    port: {{.Values.edgex.port.appservice.apprecordreplay}}
  selector:
    org.edgexfoundry.service: {{.Values.edgex.app.appservice.apprecordreplay}}
  type: {{.Values.expose.type.appservice.apprecordreplay}}
