apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingre
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: god.local
    http:
      paths:
      - path: /core-data(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: edgex-core-data
            port:
              number: 59880
      - path: /core-command(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: edgex-core-command
            port:
              number: 59882
      - path: /core-metadata(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: edgex-core-metadata
            port:
              number: 59881
      - path: /
        pathType: Prefix
        backend:
          service:
            name: edgex-ui
            port:
              number: 4000
