apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: nginx-ingress
data:
  "1883": "default/mqtt-service:1883"  # Maps port 1883 to the MQTT service
  "8883": "default/mqtt-service:8883" # Maps port 8883 to the MQTT service for TLS
