# Copyright (C) 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
{{- if .Values.edgex.storage.useHostPath }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edgex-consul-config-volume
spec:
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  storageClassName: ""
  claimRef:
    name: consul-config
    namespace: {{ .Release.Namespace }}
  capacity:
    storage: 8Mi
  accessModes:
    - {{.Values.edgex.storage.nonSharedVolumesAccessMode}}
  hostPath:
    path: "/mnt/edgex-consul-config"
    type: DirectoryOrCreate
    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edgex-consul-data-volume
spec:
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  storageClassName: ""
  claimRef:
    name: consul-data
    namespace: {{ .Release.Namespace }}
  capacity:
    storage: 128Mi
  accessModes:
    - {{.Values.edgex.storage.nonSharedVolumesAccessMode}}
  hostPath:
    path: "/mnt/edgex-consul-data"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edgex-db-volume
spec:
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  storageClassName: ""
  claimRef:
    name: db-data
    namespace: {{ .Release.Namespace }}
  capacity:
    storage: 512Mi
  accessModes:
    - {{.Values.edgex.storage.nonSharedVolumesAccessMode}}
  hostPath:
    path: "/mnt/edgex-db"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edgex-kuiper-data
spec:
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  storageClassName: ""
  claimRef:
    name: kuiper-data
    namespace: {{ .Release.Namespace }}
  capacity:
    storage: 128Mi
  accessModes:
    - {{.Values.edgex.storage.nonSharedVolumesAccessMode}}
  hostPath:
    path: "/mnt/edgex-kuiper-data"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edgex-kuiper-etc
spec:
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  storageClassName: ""
  claimRef:
    name: kuiper-etc
    namespace: {{ .Release.Namespace }}
  capacity:
    storage: 8Mi
  accessModes:
    - {{.Values.edgex.storage.nonSharedVolumesAccessMode}}
  hostPath:
    path: "/mnt/edgex-kuiper-etc"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edgex-kuiper-log
spec:
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  storageClassName: ""
  claimRef:
    name: kuiper-log
    namespace: {{ .Release.Namespace }}
  capacity:
    storage: 128Mi
  accessModes:
    - {{.Values.edgex.storage.nonSharedVolumesAccessMode}}
  hostPath:
    path: "/mnt/edgex-kuiper-log"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edgex-kuiper-plugins
spec:
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  storageClassName: ""
  claimRef:
    name: kuiper-plugins
    namespace: {{ .Release.Namespace }}
  capacity:
    storage: 128Mi
  accessModes:
    - {{.Values.edgex.storage.nonSharedVolumesAccessMode}}
  hostPath:
    path: "/mnt/edgex-kuiper-plugins"
    type: DirectoryOrCreate
{{- if (gt (.Values.edgex.replicas.natsserver | int) 0) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edgex-nats-data
spec:
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  storageClassName: ""
  claimRef:
    name: nats-data
    namespace: {{ .Release.Namespace }}
  capacity:
    storage: 128Mi
  accessModes:
    - {{.Values.edgex.storage.nonSharedVolumesAccessMode}}
  hostPath:
    path: "/mnt/edgex-nats-data"
    type: DirectoryOrCreate
{{- end }}
{{- if (gt (.Values.edgex.replicas.appservice.rfidllrpinventory | int) 0) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edgex-llrp-inventory-data
spec:
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  storageClassName: ""
  claimRef:
    name: llrp-inventory-data
    namespace: {{ .Release.Namespace }}
  capacity:
    storage: 128Mi
  accessModes:
    - {{.Values.edgex.storage.nonSharedVolumesAccessMode}}
  hostPath:
    path: "/mnt/edgex-llrp-inventory-data"
    type: DirectoryOrCreate
{{- end }}
{{- end }}